name: "Manual Deployment"

on: 
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment'     
        required: true
      region:
        description: 'Region'
        required: true

jobs:
  deployment:
    name: 'Manual Deployment'
    runs-on: ubuntu-latest
    # environment: dev
    steps:
      - name: 'Get AWS Account ID'
        id: aws
        uses: ./.github/actions/aws-account
        with:
          aws_profile: '${{ github.event.inputs.environment_name }}'

      - name: 'Read ACCOUNT ID'
        run: |
          echo "ACCOUNT ID: ${{ steps.aws.outputs.account_id }}"
        shell: bash