on:
  pull_request_target:
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  if_merged:
    # if: github.event.pull_request_target.merged == true
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "The PR was merged"
      shell:  bash

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: test_uploads.yaml
        pr: ${{ github.event.pull_request.number }}
        name: test.tfplan
        path: /tmp

    - name: Check downloaded artifact
      run: |
        ls -al /tmp
        ls -al /tmp/test.tfplan
        cat /tmp/test.tfplan
